### ISSUE TITLE
No backports and winreg

### ISSUE THREAD

**Issue by SuperMike96** [0xffff0800/MuddyC3v1.0.1-#2]
I'm trying to follow your reqirements.txt to install all modules, but my pip doesn't found the backports and winreg. How could I deal with it?

**Comment by 0xffff0800** [comment]
Hey SuperMike96, This was given to me as it is. From both of the leaks of panels there were some things missing that unfortunately I'm unable to provide. Thanks!

**Comment by SuperMike96** [comment]
Fine, thanks for your sharing. And do you mind share the idea of how the script works?
